function initialization()
{
  Sentence[0] = "在想當初"
  Sentence[1] = "唐朝出了一位粗魯人"
  Sentence[2] = "此人復姓尉遲"
  Sentence[3] = "單字名恭"
  Sentence[4] = "字敬德"
  Sentence[5] = "保定山後劉武周"
  Sentence[6] = "日搶三關"
  Sentence[7] = "夜奪八寨"
  Sentence[8] = "自秦王夜探白璧關"
  Sentence[9] = "敬德月下趕秦王"
  Sentence[10] = "打三鞭"
  Sentence[11] = "還兩鐧"
  Sentence[12] = "馬跳紅泥澗"
  Sentence[13] = "自降唐以來"
  Sentence[14] = "征南大戰王世充"
  Sentence[15] = "掃北收服皮克能"
  Sentence[16] = "跨海征東"
  Sentence[17] = "月下訪白袍"
  Sentence[18] = "唐王得勝"
  Sentence[19] = "班師回朝"
  Sentence[20] = "那敬德因救白袍"
  Sentence[21] = "在午門外拳打皇親李道宗"
  Sentence[22] = "打掉門牙二齒"
  Sentence[23] = "唐王惱怒"
  Sentence[24] = "貶至田莊"
  Sentence[25] = "後來白袍訪敬德"
  Sentence[26] = "那尉遲恭正在船頭獨自垂釣"
  Sentence[27] = "忽聽得身背後人又喊"
  Sentence[28] = "馬又叫"
  Sentence[29] = "言道"
  Sentence[30] = "吾乃征東薛平遼"
  Sentence[31] = "特來此地訪故交"
  Sentence[32] = "你我金殿去交旨"
  Sentence[33] = "保你為官永在朝"
  Sentence[34] = "敬德聞聽言道"
  Sentence[35] = "將軍不要認錯"
  Sentence[36] = "吾乃山野村夫"
  Sentence[37] = "耕種鋤耪一粗魯人也"
  Sentence[38] = "這是一個粗魯人"
  Sentence[39] = "你比得了嗎"

  Count = 40;
}
